export const seoKeywordsEn = [
  "Facility management company", "facility operations company", "integrated facility management", "facility operations", "facilities management services",
  "building operations management", "property operations", "property management services", "building maintenance company", "operations and maintenance company",
  "facility maintenance services", "soft services company", "technical facility management", "integrated FM services", "professional facility services",
  "commercial facility management", "property facilities management", "facility management provider", "facilities services company", "building services company",
  "Marafeq Facility Operations", "Marafeq Facility Management", "Marafeq Operations", "Marafeq maintenance", "Marafeq cleaning", "Marafeq Eastern Province",
  "Facility maintenance", "building maintenance", "property maintenance", "commercial building maintenance", "residential building maintenance", "general building maintenance",
  "facility repair services", "building repair company", "building maintenance contractor", "preventive building maintenance", "corrective maintenance services", "emergency building maintenance",
  "scheduled maintenance services", "annual maintenance contract", "comprehensive maintenance contract", "facilities maintenance contract", "building operations and maintenance",
  "common area maintenance", "commercial property maintenance", "residential property maintenance", "multi-site maintenance services", "corporate facility maintenance",
  "HVAC maintenance", "AC maintenance", "air conditioning maintenance", "air conditioner repair", "commercial HVAC maintenance", "central AC maintenance", "split AC maintenance",
  "Electrical maintenance", "building electrical maintenance", "commercial electrical contractor", "electrical repair services", "electrical systems maintenance",
  "Plumbing maintenance", "plumbing repair company", "commercial plumbing services", "building plumbing maintenance", "emergency plumber", "pipe maintenance",
  "Equipment maintenance", "appliance repair", "commercial equipment maintenance", "mechanical equipment maintenance", "restaurant equipment maintenance",
  "HVAC spare parts", "AC spare parts", "electrical spare parts", "plumbing spare parts", "equipment spare parts supplier",
  "Cleaning company", "commercial cleaning company", "building cleaning services", "facility cleaning services", "office cleaning company", "property cleaning services",
  "Deep cleaning services", "deep commercial cleaning", "deep office cleaning", "deep facility cleaning", "restaurant deep cleaning",
  "Glass cleaning", "window cleaning", "façade cleaning", "facade cleaning company", "commercial window cleaning", "building facade cleaning",
  "Property management company", "building management services", "residential property management", "commercial property management", "homeowners association management",
  "Integrated facility management", "hard FM services", "soft FM services", "technical FM", "soft facilities management", "outsourced facility management",
  "Industrial maintenance services", "factory maintenance", "plant maintenance", "industrial facility management", "industrial building maintenance",
  "Corporate facility maintenance", "office facility management", "restaurant facility management", "café maintenance services", "commercial kitchen maintenance",
  "Facility maintenance Dammam", "cleaning company Dammam", "facility management Dammam", "building maintenance Dammam", "HVAC maintenance Dammam",
  "Facility maintenance Khobar", "cleaning company Khobar", "facility management Khobar", "building maintenance Khobar", "HVAC maintenance Khobar",
  "Facility maintenance Dhahran", "industrial maintenance Dhahran", "cleaning company Dhahran", "facility management Dhahran",
  "Facility maintenance Eastern Province", "cleaning services Eastern Province", "facility management Eastern Province", "building maintenance Eastern Province"
];

export const seoKeywordsAr = [
  "إدارة مرافق", "تشغيل مرافق", "تشغيل وصيانة مرافق", "إدارة وتشغيل وصيانة المرافق", "إدارة المرافق المتكاملة", "إدارة المرافق والعقارات", "تشغيل العقارات", "إدارة الممتلكات", "إدارة المباني", "خدمات المرافق",
  "خدمات تشغيل المباني", "خدمات صيانة ونظافة", "شركة مرافق", "شركة تشغيل وصيانة", "شركة إدارة مرافق", "شركة خدمات مرافق", "شركة إدارة عقارات", "شركة خدمات عقارية وتشغيلية",
  "مرافق للتشغيل", "مرافق إدارة وتشغيل", "مرافق صيانة", "مرافق تنظيف", "مرافق الشرقية", "Marafeq",
  "صيانة مرافق", "صيانة مباني", "صيانة منشآت", "صيانة عقارات", "صيانة شاملة للمباني", "صيانة عامة للمباني", "شركة صيانة مباني", "شركة صيانة منشآت", "شركة صيانة مرافق", "مقاول صيانة مباني",
  "عقود صيانة مباني", "عقد صيانة سنوي", "عقد صيانة شامل", "عقد تشغيل وصيانة", "صيانة مواقع الشركات", "صيانة فروع الشركات", "صيانة المجمعات التجارية", "صيانة المكاتب", "صيانة اتحادات الملاك",
  "صيانة تكييف", "شركة صيانة تكييف", "صيانة مكيفات", "إصلاح مكيفات", "تنظيف مكيفات", "تركيب مكيفات", "صيانة تكييف مركزي", "صيانة وحدات التكييف", "صيانة أنظمة HVAC",
  "صيانة كهرباء", "شركة صيانة كهربائية", "كهربائي مباني", "مقاول كهرباء مباني", "صيانة أنظمة كهربائية", "إصلاح أعطال كهربائية", "فحص كهرباء المباني", "صيانة لوحات كهربائية",
  "صيانة سباكة", "شركة سباكة", "سباك مباني", "سباك طوارئ", "صيانة أنابيب", "إصلاح تسرب مياه", "كشف تسربات المياه", "معالجة تسربات المياه", "صيانة شبكات المياه", "صيانة شبكة الصرف الصحي",
  "صيانة معدات", "صيانة أجهزة", "صيانة أجهزة كهربائية", "صيانة معدات المباني", "صيانة معدات المطاعم", "صيانة معدات تجارية", "صيانة معدات صناعية",
  "قطع غيار تكييف", "قطع غيار مكيفات", "قطع غيار HVAC", "قطع غيار كهرباء", "قطع غيار سباكة", "توريد قطع غيار",
  "شركة تنظيف", "شركة تنظيف مباني", "شركة تنظيف منشآت", "شركة تنظيف مكاتب", "شركة تنظيف عقارات", "خدمات تنظيف", "خدمات نظافة", "تنظيف تجاري", "تنظيف سكني", "عقود نظافة",
  "تنظيف عميق", "شركة تنظيف عميق", "تنظيف عميق للمباني", "تنظيف شامل", "تنظيف بعد التشطيب", "تعقيم مباني", "تعقيم مكاتب",
  "تنظيف زجاج", "تنظيف واجهات", "تنظيف واجهات زجاجية", "تلميع الزجاج", "تنظيف نوافذ", "شركة تنظيف واجهات",
  "إدارة عقارات", "شركة إدارة عقارات", "إدارة مباني", "إدارة مجمعات سكنية", "إدارة مجمعات تجارية", "إدارة اتحاد ملاك", "شركة إدارة اتحاد ملاك", "تشغيل المرافق المشتركة",
  "إدارة مرافق متكاملة", "إدارة مرافق فنية", "إدارة مرافق ناعمة", "تشغيل وصيانة متكامل", "عقود إدارة مرافق",
  "صيانة مصانع", "صيانة منشآت صناعية", "تشغيل وصيانة مصانع", "خدمات مرافق صناعية", "صيانة معدات صناعية", "تنظيف مصانع", "تنظيف مستودعات",
  "شركة صيانة بالقرب مني", "أفضل شركة صيانة مباني", "شركة صيانة موثوقة", "شركة تشغيل وصيانة معتمدة", "صيانة طارئة الآن", "شركة إدارة مرافق للمجمع",
  "صيانة في الدمام", "شركة صيانة الدمام", "تنظيف الدمام", "شركة تنظيف الدمام", "إدارة مرافق الدمام", "تشغيل وصيانة الدمام",
  "شركة صيانة الخبر", "تنظيف الخبر", "إدارة مرافق الخبر", "تشغيل وصيانة الخبر", "صيانة مباني الخبر", "تنظيف مكاتب الخبر",
  "شركة صيانة الظهران", "تنظيف الظهران", "إدارة مرافق الظهران", "تشغيل وصيانة الظهران",
  "صيانة المنطقة الشرقية", "تنظيف المنطقة الشرقية", "إدارة مرافق المنطقة الشرقية", "شركة تشغيل وصيانة المنطقة الشرقية"
];
